### ISSUE TITLE
[WIP] UN Version 1.0.0 - General Ideas of United Nations

### ISSUE THREAD

**Issue by XL19860214** [Xuwei-Li/li.xuwei.un#1]
# Tasks
* [x] 1. Tech Stack Selection
* [ ] 2. Set Initiatives for UN Version 1.0.0
* [ ] 3. Sprint Planing for UN Version 0.1.0
* [ ] 10. UN Version 0.1.0 Official Launch
* [ ] 101. UN Version 1.0.0 Official Launch

### 1. Tech Stack Selection

<details><summary>Details</summary>

1. [App Agile Scrum](https://github.com/v4ex/WORKLOGS/wiki/App-Agile-Scrum) as primary dev management system.
1.1. Utilize [Artifacts](https://github.com/v4ex/WORKLOGS/wiki/App-Agile-Scrum:-Artifacts) to integrate with GitHub.
1.2. Iterate [Sprint](https://github.com/v4ex/WORKLOGS/wiki/App-Agile-Scrum:-Sprint) to achieve final goal.
2. [Cloudflare](https://cloudflare.com) as primary infrastructure provider. 
2.1. [Cloudflare Pages](https://pages.dev) for hosting Next.js Web app.
3. [Next.js](https://nextjs.org) as primary Web App framework.
3.1. [JavaScript](https://en.wikipedia.org/wiki/JavaScript), [TypeScript](https://www.typescriptlang.org) as Web App primary programming language.
3.2. Next.js App depends on [React.js](https://reactjs.org).
4. [Node.js](https://nodejs.org) as primary App runtime environment.
5. [git](https://git-scm.com) as primary Version Control System.
6. [GitHub](https://github.com) as primary Source Code Hosting and Issue Tracking System.
7. [Python](https://python.org) on local machine to collect editorial materials.
8. [Sketch Mac App](https://www.sketch.com) as primary Design Software.
9. [Visual Studio Code](https://code.visualstudio.com) as primary IDE.
10. [macOS](https://macos.apple.com) as primary development Operating System.

----------------------------------------
</details>

### 2. Set Initiatives for UN Version 1.0.0

----------------------------------------

### 3. Sprint Planning for UN Version 0.1.0

1. Import Sprint Template: Fixed Achievement Sprint
1.1. Sprint Period Limit Suggestion: 48 Hours, From UTC+8 00:00:00 to UTC-8 23:59:59
1.2. Sprint Goal: Set the primary main theme style to build the first homepage.
2. Epics
2.1. 

----------------------------------------
